# Generated by Django 4.2.16 on 2024-11-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterLevelInterface', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measurment',
            new_name='Measurement',
        ),
    ]
